services:
  auto-deploy:
    container_name: auto_deploy
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./repositories:/app/repositories
      - ${SSH_KEY_PATH:-~/.ssh/id_rsa}:/root/.ssh/id_rsa:ro  # Mount SSH key
    env_file:
      - .env
    restart: unless-stopped