services:
  auto-deploy:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./repositories:/app/repositories
      - ${SSH_KEY_PATH:-~/.ssh/id_rsa}:/root/.ssh/id_rsa:ro  # Mount SSH key
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped